apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:joaofveloso/argocd-test.git
    targetRevision: HEAD
    path: infra
destination:
  server: https://kubernetes.default.svc
  namespace: my-app

syncPolicy:
  syncOptions:
    - CreateNamespace=true

  automated:
    selfheal: true
    prune: true
